### ISSUE TITLE
moving from ctypes to cython

### ISSUE THREAD

**Issue by grburgess** [JohannesBuchner/PyMultiNest#102]
I'm thinking to try and rewrite the interface using cython to avoid some issues on different systems  with library lookup. The issue would be that it would need to find Multinest on install and would be a little more rigid when libmultinest changes. There could be some speed increases with callbacks. 

I think I will do it within pymultinest if you are interested.

**Comment by JohannesBuchner** [comment]
Sure, sounds interesting.

Could you say what the issues are that you are trying to solve? The need for putting libmultinest*.so into the library path on MacOS?

I did not use cython so far because it seemed so verbose (and I don't know it well enough). In principle one could also package multinest with the python package (compile on install).

I would not worry about MultiNest changing at this point.

**Comment by grburgess** [comment]
Mostly the need for DYLD setting and the fact that the MulitNest package is separate. 

Would we have the rights to package multinest?

**Comment by JohannesBuchner** [comment]
Yes, see the license here: https://github.com/JohannesBuchner/MultiNest/blob/master/LICENCE . Severall software packages include multinest.

**Comment by grburgess** [comment]
Nice.

Ok, well this would be a little more complicated. I’ll think about a solution.

**Comment by JohannesBuchner** [comment]
This has gone stale, but please reopen when working on it.
