### ISSUE TITLE
MultiNest 3.11 changed root to length 1000

### ISSUE THREAD

**Issue by andrewfowlie** [JohannesBuchner/PyMultiNest#107]
I noticed that MultiNest 3.11 changed the expected length of the (padded) root name from 100 to 1000. Subsequently this line

https://github.com/JohannesBuchner/PyMultiNest/blob/5d8c1036062d23ed22d8c00d544b8103ec478baa/pymultinest/run.py#L233

may need changing to 1000. In C-interfaces I find I/O errors if I don’t update to 1000. I haven’t checked pymultinest yet, but anticipate the same problem.

**Comment by JohannesBuchner** [comment]
If someone tests what happens when increasing the limit to 1000 with older multinest versions, I might consider altering this. Until we know that, I recommend not using long names and avoiding them with symlinks or by cd-ing into the directory. Sorry, I didn't invent the 100 char limit in the first place and am only trying to keep backward compatibility.

**Comment by smfactor** [comment]
A solution I've found is to use [tempfile.mkdtemp](https://docs.python.org/2/library/tempfile.html#tempfile.mkdtemp) to create a temporary working directory then move it to the correct path after multinest is done. It's a bit hackey but it works.
