### ISSUE TITLE
No mode identification with Importance nested samling

### ISSUE THREAD

**Issue by fzeiser** [JohannesBuchner/PyMultiNest#116]
Note: This is not an issue any longer, but because I wasted some hours trying to find out of it, I though I document it here. Also, I'll follow up with a question.

I tried to run PyMultinest with the eggbox example `pymultinest_demo.py`. Visualizing the results with `multinest_marginals.py`, one clearly sees that there is several different modes. However, I was surprised that `get_mode_stats()` would only find one mode. This seemed contradictory.

The reason for it is that PyMultinest uses _Importance Nested Sampling_ by default, and as the readme states, one should then really read the readme to Multinest, too!
https://github.com/JohannesBuchner/PyMultiNest/blob/5d8c1036062d23ed22d8c00d544b8103ec478baa/pymultinest/run.py#L106-L108

> Multi-Modal Mode:
> Multi-modal mode is not supported yet when `IS = T`. If `mmodal = T` along with `IS = T`, MultiNest will set `mmodal = F`.
https://github.com/JohannesBuchner/MultiNest/blob/f6c6df735dd78bae58e053522b04f26a21947591/README#L447-L449

So the mode identification (= "multi-modal mode") is turned off, if you run PyMultinest with the default parameters. One you turn off `IS` (Importance nested sampling), and set proper limits on the `mode_tolerance`, the mode identification will work again; you can see this eg in the `3-stats.dat` file produced when running `pymultinest_demo.py`, where I replace input to `solve` by

```
# run MultiNest
result = solve(LogLikelihood=myloglike, Prior=myprior, n_dims=n_params, outputfiles_basename=prefix, verbose=True, 
	importance_nested_sampling=False, mode_tolerance=200)
```
Start of `3-stats.dat`:
```
[...]
Local Mode Properties
-------------------------------------------

Total Modes Found:          17


Mode   1
Strictly Local Log-Evidence    0.233106816546603255E+03 +/-    0.749674653061068841E+00
Local Log-Evidence    0.233106816546603255E+03 +/-    0.150880901703714404E+00
[...]
```

**Comment by fzeiser** [comment]
Now, it's clearly stated in the readme, that `mmode` together with `IS`is not supported (yet). Do you know why that's the case? I had my difficulties to find an explanation in the arXiv article.

**Comment by JohannesBuchner** [comment]
Normal MultiNest, when its finds distinct clusters, starts independent runs on those (filling each with nlive points). That's how it can report in the end evidence values for each mode, because it ran on them independently.

With INS, the clusters at each likelihood threshold are interpreted as a importance sampling proposal distribution. It's not easily possible to do the breaking up and summing then (not sure why exactly).

I am thinking about changing the default away from INS. In my experience INS gives unrealistically small uncertainties (see for example, https://arxiv.org/abs/1806.04683). The difference between NS and INS estimates can be quite helpful though.

**Comment by JohannesBuchner** [comment]
Thanks for documenting and opening the issue.

**Comment by fzeiser** [comment]
Thanks for the answer! Well, it's fine for me if you close the issue here; it was really mostly for documentation if someone else is too stupid to follow along in the readme.
