### ISSUE TITLE
High dimension spaces with constraints

### ISSUE THREAD

**Issue by awsteiner** [JohannesBuchner/PyMultiNest#170]
My particular problem is 30-dimensional, and monomodal (fortunately), but has several constraints. I handle these constraints in pymultinest by giving points which violate them a very small likelihood. Unfortunately, because of the high dimension, a trivial execution of pymultinest always gives points outside the valid region. Basically, because of the high dimension, pymultinest can never find the location where the probability is most significant. Is there a way to give pymultinest one (or several) initial points so it can better handle the problem?

**Comment by rpoleski** [comment]
I remember I've once checked it in original MultiNest code. The initial points were randomly drawn and there was no "hook" that allowed providing starting points. I agree that it would be convenient to be able to provide starting points. I guess you can try increasing number of live points to increase chances that correct solution is found, etc., but such tricks won't work in each case.

**Comment by awsteiner** [comment]
Yeah the dimensionality is so high that increasing the number of live points would be extremely time consuming...

**Comment by JohannesBuchner** [comment]
I suggest you define the likelihood so that it increases towards the region which fulfills the constraint.

If you are inside the constraint, use the real likelihood value. logaddexp may also be useful.

Multinest has a feature where small likelihood values <-1e90 by default IIRC are ignored and resampled, so you may want to steer clear of that or lower that threshold.

**Comment by awsteiner** [comment]
Oh I see yes that could work. Thank you Johannes.
