### ISSUE TITLE
Q: why is n_params necessary?

### ISSUE THREAD

**Issue by pcubillos** [JohannesBuchner/PyMultiNest#240]
Hi, just a question in `solve()` function:
I guess I don't really understand why line 43 is necessary if the `SafePrior()` function provides the `nparams` argument? Shouldn't `n_params` be the same?
https://github.com/JohannesBuchner/PyMultiNest/blob/e82832cfeeb9b223b03063d4cc8d37e3b1837c85/pymultinest/solve.py#L41-L47

Thanks.

**Comment by JohannesBuchner** [comment]
I think the issue was that you can get segfaults if the integer variable behind ndim or nparams gets garbage-collected by python. see https://github.com/JohannesBuchner/PyMultiNest/issues/5 
Accessing the python variable always works around that, but yes, probably line 43 could be pulled out of the function.

**Comment by pcubillos** [comment]
Ahh, I see. Thanks for the explanation and link.
