### ISSUE TITLE
PyMultiNest MacOS arm64 installation

### ISSUE THREAD

**Issue by sahiljhawar** [JohannesBuchner/PyMultiNest#255]
@JohannesBuchner Here's a CI (https://github.com/sahiljhawar/pmn-ci/) which successfully builds MultiNest and PyMultiNest on arm based Mac. Do you mind adding this to PMN test suite?

**Comment by JohannesBuchner** [comment]
Sounds good to me, can you please make a pull request?

The first half makes sense for a build CI workflow. But lets skip testing the install via conda, because if that breaks, it is potentially not resolvable from this github repo, and it should be tested at https://github.com/conda-forge/pymultinest-feedstock and https://github.com/conda-forge/multinest-feedstock
