### ISSUE TITLE
evtol

### ISSUE THREAD

**Issue by jtlz2** [JohannesBuchner/PyMultiNest#57]
@JohannesBuchner For me evtol has zero effect on the size of the evidence uncertainties - the only way I can find to reduce them is to increase the number of live points. Am I doing something wrong? Do you see the same behaviour? Thanks!

**Comment by JohannesBuchner** [comment]
Are you using INS (importance_nested_sampling)?

**Comment by JohannesBuchner** [comment]
The uncertainty is a combination of systematic uncertainty (due to the step size from the number of live points, occuring during the integration) and the integration remainder uncertainty (due to how far up you integrate). If the first dominates, you have to increase the number of live points. The tolerance is the stopping criterion, but it can not fix the error occuring during the integration, afterwards.
