### ISSUE TITLE
evidence_tolerance --> how to put the stopping criterion?

### ISSUE THREAD

**Issue by ffinger** [JohannesBuchner/PyMultiNest#58]
My PyMultiNest runs seem to run very well for my problem, and I can find higher logLikelihood values than with any other method (emcee for example). However, the acceptance ratio decreases rapidly, and after some 20 to 30k accepted points (with const_efficiency_mode=True and n_live_points=1000) the likelihood does not increase any more. I believe that this happens close to the global maximum, however multinest tries to go further and does not stop. I tried to increase evidence_tolerance, but I can not figure out what is a reasonable value for it. What does this stopping criterion represent? How high should I put it if I am interested only in the posterior samples? My best logLikelihood values are around -53000, which should be close to the optimum I guess.
Also, if I stop the run manually or via the max_iter parameter the post_equal_weights.dat contains only one line, instead of a sample of the posterior. Is this normal? How are these posterior samples created? Can I do this manually? How is the number of points in the posterior sample determined?
Thanks

**Comment by JohannesBuchner** [comment]
Your questions are essentially all MultiNest questions, but I may be able to answer them anyways.

The acceptance rate will decrease rapidly because the region where higher likelihoods can be sampled from becomes very small.

I wrote an explanation how nested sampling works here http://arxiv.org/abs/1407.5459, which you might find enlightening.

const_efficiency_mode is not recommended. Try smaller n_live_points to speed things up, e.g. I usually only use 400.

You may choose the stopping criterion as evidence_tolerance=5. If it terminates too early, you can change it and resume with resume=True.

You will see how your posterior samples are distributed. If you have too few live points, or too high tolerance, you will have only have a few points (those with high likelihood dominate). So your pdf will be poorly sampled. That's why post_equal_weights.dat may only contain one value (the one with the highest likelihood), whose posterior weight is larger than that of all other points taken together.

"How is the number of points in the posterior sample determined?" I actually don't know. If everything went well, the number of samples should be around ~4000 (regardless of the chosen number of live points).

**Comment by ffinger** [comment]
Thank you very much for your reply.
I did as you said and tried without the const_efficiency_mode and with only 400 live points. I still get the same proble, that the sampling goes to very good log-likelihood values, but the algorithm does not stop even after a very high number of model evaluations. Looking at the [root].txt output file I indeed observe that there is one point which concentrates more than 99.9% of the weight, whereas the other points have very low weights. The strange thing is that all points have very similar parameter and likelihood values anyway, so I do not understand why the weight is so different. I guess that's why there is only one point in the post_equal_weights.dat file.
I guess this is a problem of my likelihood function then? Can it be related to the fact that the expected best likelihood is a quite high negative number (-52700)? Or is the weighting and the stopping criterion completely scale independent?

**Comment by JohannesBuchner** [comment]
-52700 is not a high number, -1e90 would be a problem. 

The likelihood values are very similar? At the end of the run they should be <0.5 apart. Very strange. 

Can you post some example output (e.g. print the likelihood value you return in your likelihood function) and perhaps some files (e.g. .txt, post_equal_weights.dat)?

**Comment by ffinger** [comment]
My likelihood function is computed depending on the output of a model, e.g. something like
logLK=log(sum_of_square_errors(data,model))

     At the end of the run they should be <0.5 apart.

Does this mean that the stopping criterion of 0.5 is applied to the likelihood value? If I increase the value it will stop earlier? And get more points?

Files are here:
https://enacshare.epfl.ch/dZk4Fpiu9YcRwrLbBqsaP

**Comment by JohannesBuchner** [comment]
No. I was just quoting a rough number for orientation. You said the likelihood values are very similar, but how similar are they?

![test](https://cloud.githubusercontent.com/assets/51015/8449365/3eec3ab0-1fa7-11e5-8b03-09396905dc01.png)

Your best likelihood is leading the others by ~10. The error you will get on your evidence will be large (maybe 10dex, but hard to say). Your run is simply not done yet.

**Comment by JohannesBuchner** [comment]
You could try evidence_tolerance=100, but do check the uncertainty you get on the evidence Z.

**Comment by ffinger** [comment]
If I don't need the evidence, but an estimate of the shape of the 
posterior, is there a way of accelerating? It is still running, but the 
acceptance rate is extremely low now, so that I think it will never be 
done.

**Comment by JohannesBuchner** [comment]
Hmm. You could reduce the number of parameters, or reduce the ranges of the priors.

Looking at the .txt file (splot "06-.txt" u 3:4:(-0.5*$2) in gnuplot), for example:
```
0.6 - 1.3
1e-6   - 1e-2
0.06 - 0.15
2.5 - 15
0.2 - 0.5
0.25 - 0.55
0.07 - 0.12
690 - 860
0.05 - 0.065
```
Strange though, that with just 9 parameters the efficiency is so low (how low? 0.0001?). This might be an interesting test problem for developing better algorithms!
You could also consider running emcee or polychord. If you can rewrite your problem into the Stan language, you would be able to take advantage of the best MCMC sampler.

**Comment by ffinger** [comment]
Well, going into the resume file I find that there have been  17100 
accepted points out of  2334939 trials so far. How is this compared to 
other problems?
How is the sampling done? Take a random point from the prior and then 
see if it is within the ellipse? Or something more intelligent?

**Comment by JohannesBuchner** [comment]
It is more intelligent than that. First it clusters the existing points, makes ellipses around, then draws from within the ellipse. (Btw, to check whether a random point is within the ellipse, no likelihood evaluation is necessary).

17100 / 2334939 ~= 0.7%  ... I have seen worse, but it certainly is not good! Especially since you only have 9 parameters.
